services:
  postgres:
    image: timescale/timescaledb:2.13.0-pg16
    container_name: llmpricing_postgres
    environment:
      POSTGRES_USER: llmpricing
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: llmpricing_dev
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U llmpricing"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - llmpricing-network

  redis:
    image: redis:7-alpine
    container_name: llmpricing_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - llmpricing-network

volumes:
  pgdata:

networks:
  llmpricing-network:
    driver: bridge
